version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run-script build
artifacts:
  files:
    - '**/*'
  base-directory: build  
  name: stackemblocks-$(date +%Y-%m-%d::%H:%M:%S%s) 