version: 0.2

env:
  variables:
    NODE_ENV: "${env}"

phases:
  install:
    commands:
      - npm install
  pre_build:
    commands: 
      - npm run-script lint
      - npm run-script run-unit-tests   
  build:
    commands:
      - npm run-script build

artifacts:
  files:
    - '**/*'
  base-directory: build
  name: stackemblocks-$(date +%Y-%m-%d::%H:%M:%S%s) 